(
  (kind semantic_datatype)
  (id json_value)
  (label Json)
  (description "A value expressible using the JSON data model, independent of its serialized representation.")
  (implements (
    (information ())
  ))
  (implementedBy (
    (json_object ())
  ))
  (preferredImplementation json_object)
  (inheritsFrom (
    (information (
      (borrow ([]
        *
      ))
      (exclude ([]))
    ))
  ))
)
